// Extract Finnish sentences with English translations from the cheat sheet
// Organized by categories

const sentences = [
    // 💬 EMOTIONS & REACTIONS
    { finnish: "Miltä kuulostaa?", english: "How does it sound?", category: "Emotions & Reactions" },
    
    // 💪 SUPPORT / HELP
    { finnish: "Minä tuen sinua.", english: "I support you.", category: "Support & Help" },
    { finnish: "Autan sinua tekemään kotitehtävää.", english: "I help you do homework.", category: "Support & Help" },
    { finnish: "Autan sinua laittamaan ruokaa.", english: "I help you cook food.", category: "Support & Help" },
    { finnish: "Voisitko auttaa minua projektissa?", english: "Could you help me with the project?", category: "Support & Help" },
    { finnish: "Voisitko auttaa minua opiskelussa?", english: "Could you help me with studying?", category: "Support & Help" },
    
    // 😰 WORRY / STRESS / ENCOURAGEMENT
    { finnish: "Olen huolissani tentistä.", english: "I am worried about the test.", category: "Worry & Stress" },
    { finnish: "Olen täysin varma, että läpäiset testin.", english: "I am completely sure that you will pass the test.", category: "Worry & Stress" },
    { finnish: "Sä pystyt siihen!", english: "You can do it!", category: "Worry & Stress" },
    
    // 🙏 REQUESTS / PYNNÖT
    { finnish: "Pyydän apua sinulta.", english: "I ask for help from you.", category: "Requests" },
    { finnish: "Pyydän kynän ystävältäni.", english: "I ask for a pen from my friend.", category: "Requests" },
    { finnish: "Pyydän äitiä laittamaan ruokaa.", english: "I ask mother to cook food.", category: "Requests" },
    { finnish: "Pyydän häntä viemään minut lentoasemalle.", english: "I ask him/her to take me to the airport.", category: "Requests" },
    { finnish: "Voisitko pyytää lasta olemaan hiljaa?", english: "Could you ask the child to be quiet?", category: "Requests" },
    { finnish: "Minulla olisi pyyntö sinulle.", english: "I would have a request for you.", category: "Requests" },
    { finnish: "Olisin kiitollinen tiedosta.", english: "I would be grateful for the information.", category: "Requests" },
    
    // 🐈 DAILY LIFE / ACTIONS
    { finnish: "Voisitko ruokkia kissaa joka päivä?", english: "Could you feed the cat every day?", category: "Daily Life" },
    { finnish: "Pysyin koko päivän kotona.", english: "I stayed home all day.", category: "Daily Life" },
    { finnish: "Pysyä terveenä.", english: "Stay healthy.", category: "Daily Life" },
    { finnish: "Olen poissa kotoa huomenna.", english: "I am away from home tomorrow.", category: "Daily Life" },
    
    // 😡 COMPLAINTS / VALITUS
    { finnish: "Jos se käy uudestaan, soitan isännöitsijälle.", english: "If it happens again, I will call the property manager.", category: "Complaints" },
    { finnish: "Voisitko olla huutamatta?", english: "Could you stop shouting?", category: "Complaints" },
    
    // 😔 APOLOGIES / ANTEEKSIPYYNTÖ
    { finnish: "Jätin kirjan bussiin.", english: "I left the book on the bus.", category: "Apologies" },
    { finnish: "Kirja jäi bussiin.", english: "The book was left on the bus.", category: "Apologies" },
    { finnish: "Jouduin odottamaan bussia.", english: "I had to wait for the bus.", category: "Apologies" },
    { finnish: "Jouduin perumaan kokouksen.", english: "I had to cancel the meeting.", category: "Apologies" },
    { finnish: "Matka kesti kauan.", english: "The trip took a long time.", category: "Apologies" },
    { finnish: "Matka kesti kauemmin.", english: "The trip took longer.", category: "Apologies" },
    
    // 🧠 THINKING / OPINION (Mielipide)
    { finnish: "Mietin, miksi he ovat ujompia.", english: "I wonder why they are shyer.", category: "Thinking & Opinion" },
    { finnish: "Minua kiinnostaa, miksi suomalaiset ovat hiljaisia.", english: "I am interested in why Finns are quiet.", category: "Thinking & Opinion" },
    { finnish: "Olen täysin samaa mieltä.", english: "I completely agree.", category: "Thinking & Opinion" },
    { finnish: "Olen osittain samaa mieltä.", english: "I partially agree.", category: "Thinking & Opinion" },
    { finnish: "Olen eri mieltä.", english: "I disagree.", category: "Thinking & Opinion" },
    
    // 💡 OTHER VERB PATTERNS
    { finnish: "Unelmoin koirasta.", english: "I dream about a dog.", category: "Verb Patterns" },
    { finnish: "Unelmoin lääkärin urasta.", english: "I dream about a doctor's career.", category: "Verb Patterns" },
    { finnish: "Työ sujuu hyvin.", english: "Work is going well.", category: "Verb Patterns" },
    { finnish: "Projekti sujuu hitaasti.", english: "The project is progressing slowly.", category: "Verb Patterns" },
    
    // 🌍 LIFE & WORLD / GENERAL TOPICS
    { finnish: "Maailma on muuttunut sadassa vuodessa.", english: "The world has changed in a hundred years.", category: "Life & World" },
    { finnish: "On tutkittu, että joka toisella ihmisellä on lemmikki.", english: "It has been researched that every other person has a pet.", category: "Life & World" },
    
    // ⚙️ GRAMMAR STRUCTURES
    { finnish: "Jos haluaa ostaa asunnon, pitää säästää rahaa.", english: "If one wants to buy an apartment, one must save money.", category: "Grammar" },
    { finnish: "Jos asuu vuokra-asunnossa, ei tarvitse huolehtia remontista.", english: "If one lives in a rental apartment, one doesn't need to worry about renovations.", category: "Grammar" },
    { finnish: "Suomessa juodaan paljon kahvia.", english: "A lot of coffee is drunk in Finland.", category: "Grammar" },
    { finnish: "Ennen luettiin enemmän kuin nykyään.", english: "People used to read more than nowadays.", category: "Grammar" },
    { finnish: "Nykyään ostetaan liikaa vaatteita.", english: "Nowadays too many clothes are bought.", category: "Grammar" },
    
    // ⚖️ CONTRAST / CONNECTORS
    { finnish: "Minulla on sekä kissa että koira.", english: "I have both a cat and a dog.", category: "Contrast & Connectors" },
    { finnish: "Sekä miehillä että naisilla on samat oikeudet.", english: "Both men and women have the same rights.", category: "Contrast & Connectors" },
    { finnish: "Haluaisin hankkia joko koiran tai kissan.", english: "I would like to get either a dog or a cat.", category: "Contrast & Connectors" },
    { finnish: "Koulutus Suomessa on ilmaista, kun taas Aasiassa se on maksullista.", english: "Education in Finland is free, whereas in Asia it is paid.", category: "Contrast & Connectors" },
    
    // ➕ ADDING IDEAS
    { finnish: "Minulla on muun muassa koira.", english: "I have, among other things, a dog.", category: "Adding Ideas" },
    { finnish: "Rahalla voi muun muassa matkustaa.", english: "With money one can, among other things, travel.", category: "Adding Ideas" },
    
    // 🏁 STRUCTURE / CONNECTIVES
    { finnish: "Lopuksi on tärkeää sanoa.", english: "Finally, it is important to say.", category: "Structure & Connectives" },
    { finnish: "Lopuksi on tärkeää lisätä.", english: "Finally, it is important to add.", category: "Structure & Connectives" },
    { finnish: "Lopuksi on tärkeää mainita.", english: "Finally, it is important to mention.", category: "Structure & Connectives" },
    { finnish: "Kuten tiedät, se on suosittua.", english: "As you know, it is popular.", category: "Structure & Connectives" },
    { finnish: "Voisit vaikkapa tulla mukaan.", english: "You could, for example, come along.", category: "Structure & Connectives" },
    
    // 🔜 AIKOMUS (Intentions)
    { finnish: "Mä aion levätä koko viikon.", english: "I'm going to rest the whole week.", category: "Intentions & Time" },
    { finnish: "Mä meinaan levätä koko viikon.", english: "I'm going to rest the whole week.", category: "Intentions & Time" },
    
    // 🕰️ AJASTA KYSYMINEN (Time Questions)
    { finnish: "Milloin on meidän kokous?", english: "When is our meeting?", category: "Intentions & Time" },
    { finnish: "Koska on meidän kokous?", english: "When is our meeting?", category: "Intentions & Time" },
    { finnish: "Mihin aikaan korjaaja tulee?", english: "What time does the repair person come?", category: "Intentions & Time" },
    { finnish: "Mihin asti YKI-todistus on voimassa?", english: "Until when is the YKI certificate valid?", category: "Intentions & Time" },
    { finnish: "Iltaan asti.", english: "Until evening.", category: "Intentions & Time" },
    { finnish: "Ensi viikkoon asti.", english: "Until next week.", category: "Intentions & Time" },
    { finnish: "Eilisestä alkaen.", english: "Starting from yesterday.", category: "Intentions & Time" },
    { finnish: "Huomisesta alkaen minulla projekti.", english: "Starting from tomorrow I have a project.", category: "Intentions & Time" },
    { finnish: "Viikon kuluttua.", english: "In a week.", category: "Intentions & Time" },
    { finnish: "Viiden minuutin päästä.", english: "In five minutes.", category: "Intentions & Time" },
    { finnish: "Kahden viikon päästä.", english: "In two weeks.", category: "Intentions & Time" },
    { finnish: "Kuinka pitkäksi ajaksi menet lomalle?", english: "For how long are you going on vacation?", category: "Intentions & Time" },
    { finnish: "Viime kerralla olin unelias.", english: "Last time I was dreamy.", category: "Intentions & Time" },
    { finnish: "Viime vuonna olimme Espanjassa.", english: "Last year we were in Spain.", category: "Intentions & Time" },
    { finnish: "Ensi kerralla sinä läpäiset YKI-testin.", english: "Next time you will pass the YKI test.", category: "Intentions & Time" },
    
    // 🏢 KELA & ETUUDET (Benefits)
    { finnish: "Opintotukea maksetaan opiskelijoille.", english: "Student allowance is paid to students.", category: "KELA & Benefits" },
    { finnish: "Lapsilisää maksetaan vanhemmille.", english: "Child benefit is paid to parents.", category: "KELA & Benefits" },
    { finnish: "Eläkettä maksetaan eläkeläisille.", english: "Pension is paid to pensioners.", category: "KELA & Benefits" },
    { finnish: "Sinun on ilmoitettava tulorajan ylittymisestä.", english: "You must report the exceeding of the income limit.", category: "KELA & Benefits" },
    { finnish: "Tukeni on laskenut tänä vuonna.", english: "My benefit has decreased this year.", category: "KELA & Benefits" },
    { finnish: "Tuloraja ylittyi.", english: "The income limit was exceeded.", category: "KELA & Benefits" },
    { finnish: "Tulo ylittää rajan.", english: "Income exceeds the limit.", category: "KELA & Benefits" },
    { finnish: "Käsittelyaika on enintään kaksi kuukautta.", english: "Processing time is at most two months.", category: "KELA & Benefits" },
    { finnish: "Käsittelyaika on ainakin kaksi kuukautta.", english: "Processing time is at least two months.", category: "KELA & Benefits" },
    { finnish: "Voin maksaa enintään tuhat euroa.", english: "I can pay at most a thousand euros.", category: "KELA & Benefits" },
    { finnish: "Tulo ei vaikuta opintotukeen.", english: "Income does not affect student allowance.", category: "KELA & Benefits" },
    { finnish: "Anteeksi, voisitko toistaa?", english: "Sorry, could you repeat?", category: "KELA & Benefits" },
    
    // 🔗 SYY–SEURAUS & PERUSTELU (Cause & Effect)
    { finnish: "Nykyään masennus on yleinen ongelma, sillä elämässä on paljon vaikeuksia.", english: "Nowadays depression is a common problem, because life has many difficulties.", category: "Cause & Effect" },
    { finnish: "Joten minun pitää opiskella ahkerasti.", english: "So I must study diligently.", category: "Cause & Effect" },
    { finnish: "Olen aina ollut kiinnostunut taiteesta.", english: "I have always been interested in art.", category: "Cause & Effect" },
    
    // 📈 VAIKUTUS / SEURAUS -VERBIT (Impact Verbs)
    { finnish: "Liikunta vaikuttaa sydämeen positiivisesti.", english: "Exercise affects the heart positively.", category: "Impact Verbs" },
    { finnish: "Sokeri aiheuttaa erittäin voimakasta riippuvuutta.", english: "Sugar causes very strong addiction.", category: "Impact Verbs" },
    { finnish: "Myrsky aiheutti vaarallisen tilanteen.", english: "The storm caused a dangerous situation.", category: "Impact Verbs" },
    { finnish: "Jatkuva stressi johtaa terveysongelmiin.", english: "Continuous stress leads to health problems.", category: "Impact Verbs" },
    { finnish: "Nälkä johtaa kuolemaan.", english: "Hunger leads to death.", category: "Impact Verbs" },
    { finnish: "Tämä johtaa kipuun.", english: "This leads to pain.", category: "Impact Verbs" },
    { finnish: "Kova työ johtaa menestykseen.", english: "Hard work leads to success.", category: "Impact Verbs" },
    
    // 🧠 IDIOMATIIKKA & TUNTEET (Idioms & Feelings)
    { finnish: "Elämä tuntuu oravanpyörältä.", english: "Life feels like a hamster wheel.", category: "Idioms & Feelings" },
    { finnish: "Kun arki on kiireistä, elämä tuntuu oravanpyörältä.", english: "When daily life is busy, life feels like a hamster wheel.", category: "Idioms & Feelings" },
    { finnish: "Ihmisten pitää ehtiä paljon: viedä lapset päiväkotiin, saada projekti valmiiksi, mennä lääkäriin, mennä kauppaan.", english: "People must manage a lot: take children to daycare, finish the project, go to the doctor, go to the store.", category: "Idioms & Feelings" },
    { finnish: "Olen myöhässä tapaamisesta.", english: "I am late for the meeting.", category: "Idioms & Feelings" },
    { finnish: "Jos mieli on maassa, pitää pysähtyä rauhoittumaan.", english: "If one is down, one must stop to calm down.", category: "Idioms & Feelings" },
    { finnish: "On tärkeää löytää tasapaino elämässä.", english: "It is important to find balance in life.", category: "Idioms & Feelings" },
    { finnish: "Kun mieli on maassa, käyn terapeutilla.", english: "When I'm down, I go to therapy.", category: "Idioms & Feelings" },
    { finnish: "Jos mulla on paljon töitä kesken, se aiheuttaa stressiä.", english: "If I have a lot of work unfinished, it causes stress.", category: "Idioms & Feelings" },
    { finnish: "Tämä on vaikea kysymys, johon ei ole oikeaa vastausta.", english: "This is a difficult question to which there is no right answer.", category: "Idioms & Feelings" },
    { finnish: "Nykyihmiset haluavat oppia uusia asioita ja ansaita paljon rahaa.", english: "Modern people want to learn new things and earn a lot of money.", category: "Idioms & Feelings" },
    { finnish: "Tämä johtaa stressiin ja ahdistukseen.", english: "This leads to stress and anxiety.", category: "Idioms & Feelings" },
    { finnish: "Jos mieli on maassa, pitää pysähtyä rauhoittumaan ja yrittää nauttia nykyhetkestä.", english: "If one is down, one must stop to calm down and try to enjoy the present moment.", category: "Idioms & Feelings" },
    { finnish: "On tärkeää löytää tasapaino elämässä ja ymmärtää, että elämässä on muutakin kuin työ.", english: "It is important to find balance in life and understand that there is more to life than work.", category: "Idioms & Feelings" },
    
    // 🏦 PANKKI (Bank)
    { finnish: "Tallettan rahaa tilille.", english: "I deposit money to the account.", category: "Bank" },
    { finnish: "Nostin 50 euroa automaatista.", english: "I withdrew 50 euros from the ATM.", category: "Bank" },
    { finnish: "Siirsin rahaa ystävälle.", english: "I transferred money to a friend.", category: "Bank" },
    { finnish: "Siirsin rahaa toiselle tilille.", english: "I transferred money to another account.", category: "Bank" },
    { finnish: "Kadotin pankkikorttini eilen.", english: "I lost my bank card yesterday.", category: "Bank" },
    { finnish: "Kortti katosi lentoasemalla.", english: "The card disappeared at the airport.", category: "Bank" },
    { finnish: "Menetin korttini, en tiedä missä.", english: "I lost my card, I don't know where.", category: "Bank" },
    { finnish: "Jätin kortin pöydälle.", english: "I left the card on the table.", category: "Bank" },
    { finnish: "Unohdin pankkikortin kuntosaliin.", english: "I forgot the bank card at the gym.", category: "Bank" },
    { finnish: "Voisitko kuolettaa minun kortin?", english: "Could you cancel my card?", category: "Bank" },
    { finnish: "Voisitko kuolettaa minun korttini, kiitos?", english: "Could you cancel my card, please?", category: "Bank" },
    { finnish: "En epäile varkautta.", english: "I don't suspect theft.", category: "Bank" },
    { finnish: "Kyseessä on kadonnut pankkikortti.", english: "It's about a lost bank card.", category: "Bank" },
    { finnish: "Haluan hakea asuntolainaa.", english: "I want to apply for a mortgage.", category: "Bank" },
    { finnish: "Haluan kysyä, miten voin hakea asuntolainaa?", english: "I want to ask, how can I apply for a mortgage?", category: "Bank" },
    { finnish: "Mitä asiakirjoja tarvitaan?", english: "What documents are needed?", category: "Bank" },
    { finnish: "Kuinka pitkäksi ajaksi voi saada lainaa?", english: "For how long can one get a loan?", category: "Bank" },
    
    // 🏠 VAKUUTUSYHTIÖ (Insurance)
    { finnish: "Korvaako vakuutus tämän vahingon?", english: "Does the insurance cover this damage?", category: "Insurance" },
    { finnish: "Omavastuu on 200 euroa.", english: "The deductible is 200 euros.", category: "Insurance" },
    { finnish: "Vakuutus korvaa vaurion.", english: "The insurance covers the damage.", category: "Insurance" },
    { finnish: "Tämä paketti kattaa myös luonnonilmiöt.", english: "This package also covers natural phenomena.", category: "Insurance" },
    { finnish: "Vahinko aiheutui myrskystä.", english: "The damage was caused by a storm.", category: "Insurance" },
    { finnish: "Jouduin kolariin työmatkalla.", english: "I got into an accident on the way to work.", category: "Insurance" },
    { finnish: "Loukkaannuin käteen.", english: "I injured my hand.", category: "Insurance" },
    { finnish: "Loukkasin itseni käteen.", english: "I injured myself in the hand.", category: "Insurance" },
    { finnish: "Haluaisin hakea korvausta lääkärikuluista.", english: "I would like to claim compensation for doctor's costs.", category: "Insurance" },
    { finnish: "Voit valita S-, M- tai L-paketin.", english: "You can choose S-, M- or L-package.", category: "Insurance" },
    { finnish: "Voisitko selittää, mitä tarkoittaa rikkoutumisturva?", english: "Could you explain what breakdown insurance means?", category: "Insurance" },
    { finnish: "Se oli äkillinen ja arvaamaton vahinko.", english: "It was a sudden and unpredictable damage.", category: "Insurance" },
    
    // 🧾 VEROTOIMISTO (Tax Office)
    { finnish: "Verotuspäätöksessä lukee, että prosentti on 40.", english: "The tax decision says that the percentage is 40.", category: "Tax Office" },
    { finnish: "Sopimuksessa lukee, että vuokra on 1000 euroa.", english: "The contract says that the rent is 1000 euros.", category: "Tax Office" },
    { finnish: "Verottaja päätti uudesta veroprosentista.", english: "The tax authority decided on a new tax percentage.", category: "Tax Office" },
    { finnish: "Sain veronpalautuksen joulukuussa.", english: "I received the tax refund in December.", category: "Tax Office" },
    { finnish: "Hei, tässä on pikku virhe verokortissa.", english: "Hi, there is a small error in the tax card.", category: "Tax Office" },
    { finnish: "Näyttää siltä, että tässä on laskuvirhe.", english: "It looks like there is a calculation error.", category: "Tax Office" },
    { finnish: "Olin huolissani korkeasta verosta.", english: "I was worried about the high tax.", category: "Tax Office" },
    { finnish: "Tuloni on noussut tänä vuonna.", english: "My income has increased this year.", category: "Tax Office" },
    { finnish: "Tulot ovat vähentyneet.", english: "Income has decreased.", category: "Tax Office" },
    { finnish: "Olen tyytyväinen päätökseen.", english: "I am satisfied with the decision.", category: "Tax Office" },
    { finnish: "Olen huolissani virheestä.", english: "I am worried about the error.", category: "Tax Office" },
    { finnish: "Olen varma, että asia hoituu pian.", english: "I am sure that the matter will be resolved soon.", category: "Tax Office" },
    { finnish: "Vuorovaikutus on tärkeää asioidessa viranomaisen kanssa.", english: "Interaction is important when dealing with authorities.", category: "Tax Office" },
    { finnish: "Tämä päätös vaikuttaa tuloveroon.", english: "This decision affects income tax.", category: "Tax Office" },
    { finnish: "Voin rentoutua maksamalla laskut ajoissa.", english: "I can relax by paying bills on time.", category: "Tax Office" },
    { finnish: "Opin talousasioita keskustelemalla virkailijan kanssa.", english: "I learned financial matters by discussing with the official.", category: "Tax Office" },
    { finnish: "Lähdin verotoimistosta sanomatta mitään.", english: "I left the tax office without saying anything.", category: "Tax Office" },
    { finnish: "Voisitko olla valittamatta tästä päätöksestä?", english: "Could you stop complaining about this decision?", category: "Tax Office" },
    
    // 💼 TYÖELÄMÄ (Work Life)
    { finnish: "Se sopii minulle.", english: "It suits me.", category: "Work Life" },
    { finnish: "Käykö sinulle huomenna klo 10?", english: "Does tomorrow at 10 work for you?", category: "Work Life" },
    { finnish: "Onko tämä aika sinulle sopiva?", english: "Is this time suitable for you?", category: "Work Life" },
    { finnish: "Miltä kuulostaa, jos siirrämme tapaamisen ensi viikolle?", english: "How does it sound if we move the meeting to next week?", category: "Work Life" },
    { finnish: "Miltä kuulostaa, jos järjestämme juhlat Pekalle?", english: "How does it sound if we organize a party for Pekka?", category: "Work Life" },
    { finnish: "Yritys irtisanoi työntekijän.", english: "The company fired the employee.", category: "Work Life" },
    { finnish: "Minulla on pätevyys tähän tehtävään.", english: "I have the qualifications for this task.", category: "Work Life" },
    { finnish: "Hänet ylennettiin johtajaksi.", english: "He/she was promoted to manager.", category: "Work Life" },
    { finnish: "Minulla on määräaikainen sopimus kesän loppuun asti.", english: "I have a fixed-term contract until the end of summer.", category: "Work Life" },
    { finnish: "Teen osa-aikatyötä opiskelujen ohella.", english: "I do part-time work alongside studies.", category: "Work Life" },
    { finnish: "Minulla on aamuvuoro huomenna.", english: "I have a morning shift tomorrow.", category: "Work Life" },
    { finnish: "Pidän ruokatauon klo 12.", english: "I take a lunch break at 12.", category: "Work Life" },
    { finnish: "Muistutan sinua projektin deadlinesta.", english: "I remind you of the project deadline.", category: "Work Life" },
    { finnish: "Sinun pitää saada projekti valmiiksi ensi viikolla.", english: "You must finish the project next week.", category: "Work Life" },
    { finnish: "Haluan mainita yhden virheen raportissa.", english: "I want to mention one error in the report.", category: "Work Life" },
    { finnish: "Lähetin vahingossa tarjouksen väärälle asiakkaalle.", english: "I accidentally sent the quote to the wrong customer.", category: "Work Life" },
    { finnish: "Tein virheen, mutta korjaan sen heti.", english: "I made a mistake, but I will fix it immediately.", category: "Work Life" },
    { finnish: "Annoin vahingossa väärän reseptin potilaalle.", english: "I accidentally gave the wrong prescription to the patient.", category: "Work Life" },
    { finnish: "Olen jo käsitellyt asian esimiehen kanssa.", english: "I have already discussed the matter with the supervisor.", category: "Work Life" },
    { finnish: "Ehdotan, että järjestämme juhlat.", english: "I suggest that we organize a party.", category: "Work Life" },
    { finnish: "Mitä jos ostan kakun Pekalle?", english: "What if I buy a cake for Pekka?", category: "Work Life" },
    { finnish: "Mitä jos tavataan ensi viikolla?", english: "What if we meet next week?", category: "Work Life" },
    { finnish: "Matkustan Espanjaan ensi kuussa.", english: "I'm traveling to Spain next month.", category: "Work Life" },
    { finnish: "Kysy matkavakuutuksesta: mitä se kattaa, paljonko se maksaa.", english: "Ask about travel insurance: what it covers, how much it costs.", category: "Work Life" },
    { finnish: "Mitä suosittelet minulle?", english: "What do you recommend for me?", category: "Work Life" },
    { finnish: "Sain raportin valmiiksi eilen.", english: "I finished the report yesterday.", category: "Work Life" },
    { finnish: "Onko sinulla jotain hommaa kesken?", english: "Do you have some work unfinished?", category: "Work Life" },
    { finnish: "Tarvitsetko sijaisen tänään?", english: "Do you need a substitute today?", category: "Work Life" },
    { finnish: "Pikaista paranemista!", english: "Get well soon!", category: "Work Life" },
    { finnish: "Ilmoita heti, kun tiedät, kuinka pitkä sairausloma sinulle tulee.", english: "Notify immediately when you know how long your sick leave will be.", category: "Work Life" },
    { finnish: "En pysty tulemaan töihin tänään, minulla on kuume.", english: "I cannot come to work today, I have a fever.", category: "Work Life" },
    
    // 💼 ETÄTYÖ (Remote Work)
    { finnish: "Etätyö auttaa yhdistämään työtä ja vapaa-aikaa.", english: "Remote work helps combine work and free time.", category: "Remote Work" },
    { finnish: "Etätyö auttaa keskittymään ja hallitsemaan omaa aikataulua.", english: "Remote work helps focus and manage one's own schedule.", category: "Remote Work" },
    { finnish: "Etätyö yhdistää työn ja vapaa-ajan joustavasti.", english: "Remote work combines work and free time flexibly.", category: "Remote Work" },
    { finnish: "Työpäivän aikana voi kävellä koiran kanssa.", english: "During the workday one can walk the dog.", category: "Remote Work" },
    { finnish: "Etätyö helpottaa työ- ja perhe-elämän tasapainoa.", english: "Remote work eases work-life balance.", category: "Remote Work" },
    { finnish: "Etätyössä voi viettää enemmän aikaa perheen kanssa.", english: "In remote work one can spend more time with family.", category: "Remote Work" },
    { finnish: "Vietän aikaa lasteni kanssa iltapäivisin.", english: "I spend time with my children in the afternoons.", category: "Remote Work" },
    { finnish: "En käytä rahaa työmatkoihin, kun teen etätyötä.", english: "I don't spend money on commutes when I do remote work.", category: "Remote Work" },
    { finnish: "Etätyö parantaa tehokkuutta ja työn laatua.", english: "Remote work improves efficiency and work quality.", category: "Remote Work" },
    { finnish: "Etätyö kehittää itsenäistä työskentelyä.", english: "Remote work develops independent work.", category: "Remote Work" },
    { finnish: "Kotona on helpompaa keskittyä työhön.", english: "It's easier to focus on work at home.", category: "Remote Work" },
    { finnish: "Etätyö lisää työn tehokkuutta.", english: "Remote work increases work efficiency.", category: "Remote Work" },
    { finnish: "Etätyö lisää vapautta ja joustavuutta.", english: "Remote work increases freedom and flexibility.", category: "Remote Work" },
    { finnish: "Etätyössä on enemmän vapautta ja joustavuutta kuin lähityössä.", english: "In remote work there is more freedom and flexibility than in office work.", category: "Remote Work" },
    { finnish: "Etätyössä voi työskennellä kotona tai matkalla.", english: "In remote work one can work at home or while traveling.", category: "Remote Work" },
    { finnish: "Etätyö säästää työnantajan rahaa ja työntekijän aikaa.", english: "Remote work saves the employer money and the employee time.", category: "Remote Work" },
    { finnish: "Kun työskentelee etänä, ei tarvitse matkustaa paikan päälle.", english: "When working remotely, one doesn't need to travel to the location.", category: "Remote Work" },
    { finnish: "Työnantajan ei tarvitse vuokrata suurta toimistoa.", english: "The employer doesn't need to rent a large office.", category: "Remote Work" },
    { finnish: "Lähityö antaa mahdollisuuden lisätä mielen hyvinvointia.", english: "Office work gives the opportunity to increase mental well-being.", category: "Remote Work" },
    { finnish: "Minulla on mahdollisuus tehdä etätyötä.", english: "I have the opportunity to do remote work.", category: "Remote Work" },
    { finnish: "Lähityö vaikuttaa positiivisesti työyhteisöön.", english: "Office work affects the work community positively.", category: "Remote Work" },
    { finnish: "Parasta lähityössä on se, että työkaverit ovat aina tukena.", english: "The best thing about office work is that colleagues are always supportive.", category: "Remote Work" },
    { finnish: "Parasta etätyössä on se, että voi työskennellä omassa rauhassa.", english: "The best thing about remote work is that one can work in peace.", category: "Remote Work" },
    { finnish: "Tärkeintä opiskelussa on motivaatio.", english: "The most important thing in studying is motivation.", category: "Remote Work" },
    { finnish: "Tärkeintä työssä on hyvä ilmapiiri.", english: "The most important thing at work is a good atmosphere.", category: "Remote Work" },
    { finnish: "Työkaverit ovat aina tukena ja auttavat, kun ei tiedä miten jokin toimii.", english: "Colleagues are always supportive and help when one doesn't know how something works.", category: "Remote Work" },
    { finnish: "Kokenut työkaveri voi neuvoa ja tuoda iloa arkeen.", english: "An experienced colleague can advise and bring joy to everyday life.", category: "Remote Work" },
    { finnish: "Etätyö voi lisätä stressiä.", english: "Remote work can increase stress.", category: "Remote Work" },
    { finnish: "Vaikka etätyö voi tarjota joustavuutta, se voi myös lisätä stressiä.", english: "Although remote work can offer flexibility, it can also increase stress.", category: "Remote Work" },
    { finnish: "Etätyössä tuntuu joskus yksinäiseltä, erityisesti vaikeissa tehtävissä.", english: "In remote work one sometimes feels lonely, especially in difficult tasks.", category: "Remote Work" },
    { finnish: "Etätyö vähentää mahdollisuuksia tutustua työkavereihin ja oppia heiltä.", english: "Remote work reduces opportunities to get to know colleagues and learn from them.", category: "Remote Work" },
    { finnish: "Haluan tutustua uusiin työkavereihin.", english: "I want to get to know new colleagues.", category: "Remote Work" },
    { finnish: "Etätyössä on vaikeampi tutustua ihmisiin.", english: "In remote work it's harder to get to know people.", category: "Remote Work" },
    { finnish: "Kun taas lähityössä voi oppia enemmän muilta.", english: "Whereas in office work one can learn more from others.", category: "Remote Work" },
    { finnish: "Etätyö voi heikentää luovuutta ja sosiaalisia taitoja.", english: "Remote work can weaken creativity and social skills.", category: "Remote Work" },
    { finnish: "Luovuus ja yhteistyö voivat heiketä etätyössä.", english: "Creativity and cooperation can weaken in remote work.", category: "Remote Work" },
    { finnish: "Etätyö voi olla haitallista terveydelle, jos istuu koko päivän tietokoneella.", english: "Remote work can be harmful to health if one sits at the computer all day.", category: "Remote Work" },
    { finnish: "Tupakoiminen on haitallista keuhkoille.", english: "Smoking is harmful to the lungs.", category: "Remote Work" },
    { finnish: "Autot ovat haitallisia ympäristölle.", english: "Cars are harmful to the environment.", category: "Remote Work" },
    { finnish: "Sanotaan, että sininen valo on haitallista näölle.", english: "It is said that blue light is harmful to vision.", category: "Remote Work" },
    { finnish: "Etätyö voi viedä paljon aikaa ja energiaa, jos työ ja vapaa-aika sekoittuvat.", english: "Remote work can take a lot of time and energy if work and free time mix.", category: "Remote Work" },
    { finnish: "Liiallinen työ voi johtaa uupumukseen.", english: "Excessive work can lead to burnout.", category: "Remote Work" },
    { finnish: "Huono ergonomia aiheuttaa selkäkipua.", english: "Poor ergonomics causes back pain.", category: "Remote Work" },
    { finnish: "Liika ruutuaika vaikuttaa negatiivisesti uneen ja keskittymiseen.", english: "Too much screen time affects sleep and concentration negatively.", category: "Remote Work" },
    { finnish: "Etätyö tuo vapautta, mutta voi lisätä yksinäisyyttä.", english: "Remote work brings freedom, but can increase loneliness.", category: "Remote Work" },
    { finnish: "Lähityö tukee vuorovaikutusta, mutta vie enemmän aikaa ja rahaa.", english: "Office work supports interaction, but takes more time and money.", category: "Remote Work" },
    { finnish: "Tärkeintä on löytää oma tasapaino työn ja elämän välillä.", english: "The most important thing is to find one's own balance between work and life.", category: "Remote Work" },
    
    // 🎓 OPISKELU (Study)
    { finnish: "Osallistun uudelle kielikurssille.", english: "I participate in a new language course.", category: "Study & Education" },
    { finnish: "Haluan ilmoittautua kurssille.", english: "I want to enroll in the course.", category: "Study & Education" },
    { finnish: "Haluan ilmoittaa koirani koirakouluun.", english: "I want to register my dog for dog school.", category: "Study & Education" },
    { finnish: "Hän hakee yliopistoon ensi vuonna.", english: "He/she is applying to university next year.", category: "Study & Education" },
    { finnish: "Pyrin yliopistoon syksyllä.", english: "I'm applying to university in the fall.", category: "Study & Education" },
    { finnish: "Opiskelen matematiikkaa.", english: "I study mathematics.", category: "Study & Education" },
    { finnish: "Opin suomea nopeasti.", english: "I learned Finnish quickly.", category: "Study & Education" },
    { finnish: "Opettelen kielioppia.", english: "I'm learning grammar.", category: "Study & Education" },
    { finnish: "Opettelen puhumaan rohkeammin.", english: "I'm learning to speak more bravely.", category: "Study & Education" },
    { finnish: "Opiskelin analyytikoksi.", english: "I studied to become an analyst.", category: "Study & Education" },
    { finnish: "Olen valmistunut yliopistosta lääkäriksi.", english: "I graduated from university as a doctor.", category: "Study & Education" },
    { finnish: "Suoritan tutkinnon ensi keväänä.", english: "I will complete the degree next spring.", category: "Study & Education" },
    { finnish: "Toivottavasti läpäiset tentin.", english: "I hope you pass the exam.", category: "Study & Education" },
    { finnish: "Jätin kurssin kesken.", english: "I dropped the course.", category: "Study & Education" },
    { finnish: "Pärjään työssä ihan hyvin.", english: "I manage quite well at work.", category: "Study & Education" },
    { finnish: "Minulla on tapana lukea iltaisin.", english: "I have a habit of reading in the evenings.", category: "Study & Education" },
    { finnish: "Olen tottunut heräämään aikaisin.", english: "I am used to waking up early.", category: "Study & Education" },
    { finnish: "En ole tottunut Suomen säähän.", english: "I am not used to Finland's weather.", category: "Study & Education" },
    { finnish: "Olen nopea oppimaan uutta.", english: "I am quick to learn new things.", category: "Study & Education" },
    { finnish: "Olen hyvä työskentelemään tiimissä.", english: "I am good at working in a team.", category: "Study & Education" },
    { finnish: "Minulla on kahden vuoden kokemus lääkärinä.", english: "I have two years of experience as a doctor.", category: "Study & Education" },
    { finnish: "Minulla on neljän vuoden kokemus data-analyytikkona.", english: "I have four years of experience as a data analyst.", category: "Study & Education" },
    { finnish: "Olen valmistunut Helsingin yliopistosta fyysikoksi.", english: "I graduated from the University of Helsinki as a physicist.", category: "Study & Education" },
    { finnish: "Olen valmistunut Panaman yliopistosta kansainvälisen liiketoiminnan asiantuntijaksi.", english: "I graduated from Panama University as an international business specialist.", category: "Study & Education" },
    { finnish: "Olen kiinnostunut tästä työpaikasta, koska voin kehittää taitojani.", english: "I am interested in this job, because I can develop my skills.", category: "Study & Education" },
    { finnish: "Ystäväni suositteli tätä tehtävää.", english: "My friend recommended this position.", category: "Study & Education" },
    { finnish: "Voisitteko kertoa tarkemmin, mitä työtehtäviin kuuluu?", english: "Could you tell me more specifically what the job duties include?", category: "Study & Education" },
    { finnish: "Vakituinen vai määräaikainen sopimus?", english: "Permanent or fixed-term contract?", category: "Study & Education" },
    { finnish: "Onko etätyö mahdollista?", english: "Is remote work possible?", category: "Study & Education" },
    { finnish: "Kenelle CV pitää lähettää?", english: "To whom should the CV be sent?", category: "Study & Education" },
    { finnish: "Milloin työ alkaa?", english: "When does the work start?", category: "Study & Education" },
    { finnish: "Minun pitää opiskella suomea.", english: "I must study Finnish.", category: "Study & Education" },
    { finnish: "Ihmisten pitäisi viettää enemmän aikaa perheen kanssa.", english: "People should spend more time with family.", category: "Study & Education" },
    { finnish: "Ihmisten kannattaa kehittää sosiaalisia taitoja.", english: "People should develop social skills.", category: "Study & Education" },
    { finnish: "Vanhempien pitää tukea lapsia opiskelussa.", english: "Parents must support children in studying.", category: "Study & Education" },
    { finnish: "Ihmisten ei tarvitse työskennellä koko ajan.", english: "People don't need to work all the time.", category: "Study & Education" },
    { finnish: "Maahanmuuttajien ei tarvitse puhua suomea täydellisesti.", english: "Immigrants don't need to speak Finnish perfectly.", category: "Study & Education" },
    { finnish: "Vanhempien ei pidä huutaa lapselle.", english: "Parents shouldn't yell at the child.", category: "Study & Education" },
    { finnish: "Yöllä ei kannata opiskella.", english: "It's not worth studying at night.", category: "Study & Education" },
    { finnish: "Vanhempien ei pitäisi pakottaa lasta harrastamaan, jos hän ei nauti siitä.", english: "Parents shouldn't force the child to do hobbies if he/she doesn't enjoy it.", category: "Study & Education" },
    { finnish: "Usein sanotaan, että lukemalla voi kehittää ammattitaitoja.", english: "It is often said that by reading one can develop professional skills.", category: "Study & Education" },
    { finnish: "Riippumatta iästä kaikki voivat opiskella.", english: "Regardless of age, everyone can study.", category: "Study & Education" },
    { finnish: "Varhaiskasvatus ja esiopetus antavat valmiuksia koulunkäyntiin.", english: "Early childhood education and pre-school give readiness for school attendance.", category: "Study & Education" },
    { finnish: "Valmistava opetus on niille, joiden suomen kieli ei vielä riitä.", english: "Preparatory education is for those whose Finnish language is not yet sufficient.", category: "Study & Education" },
    { finnish: "Perusopetuksen jälkeen haetaan toiselle asteelle.", english: "After basic education one applies to secondary level.", category: "Study & Education" },
    { finnish: "Asetan realistisen tavoitteen.", english: "I set a realistic goal.", category: "Study & Education" },
    { finnish: "Jos kiire on liikaa, motivaatio katoaa.", english: "If the rush is too much, motivation disappears.", category: "Study & Education" },
    
    // ❤️ TUNTEET (Feelings)
    { finnish: "Tunnen stressiä.", english: "I feel stress.", category: "Feelings" },
    { finnish: "Tunnen kipua.", english: "I feel pain.", category: "Feelings" },
    { finnish: "Lapsi tuntee iloa.", english: "The child feels joy.", category: "Feelings" },
    { finnish: "Minusta se tuntuu hyvältä.", english: "It feels good to me.", category: "Feelings" },
    { finnish: "Päivä tuntuu pitkältä.", english: "The day feels long.", category: "Feelings" },
    { finnish: "Silmät tuntuvat väsyneiltä.", english: "The eyes feel tired.", category: "Feelings" },
    { finnish: "Minusta sinä tunnet tutulta.", english: "You feel familiar to me.", category: "Feelings" },
    { finnish: "Minusta tuntuu, että olen yksinäinen.", english: "I feel that I am lonely.", category: "Feelings" },
    { finnish: "Tunnen itseni yksinäiseksi.", english: "I feel lonely.", category: "Feelings" },
    { finnish: "En tunne itseäni levänneeksi.", english: "I don't feel rested.", category: "Feelings" },
    { finnish: "Minulla on muutama kysymys.", english: "I have a few questions.", category: "Feelings" },
    { finnish: "Pelit pelataan vuorotellen.", english: "Games are played in turns.", category: "Feelings" },
    { finnish: "Kaipaan sinua.", english: "I miss you.", category: "Feelings" },
    { finnish: "Kaipaan Suomeen.", english: "I miss Finland.", category: "Feelings" },
    { finnish: "Minulla on kotikaipuu.", english: "I have homesickness.", category: "Feelings" },
    { finnish: "Pystyn samaistumaan tilanteeseesi.", english: "I can relate to your situation.", category: "Feelings" },
    
    // 🏫 KOULU & KERHOT (School & Clubs)
    { finnish: "Tarkista, onko paperia. Valitse tiedosto ja paina nappia.", english: "Check if there is paper. Select the file and press the button.", category: "School & Clubs" },
    { finnish: "Kerho pidetään koulun pihalla.", english: "The club is held at the school yard.", category: "School & Clubs" },
    { finnish: "Juhla järjestetään salissa.", english: "The celebration is organized in the hall.", category: "School & Clubs" },
    { finnish: "Moneltako alkaa ja loppuu?", english: "What time does it start and end?", category: "School & Clubs" },
    { finnish: "Missä pidetään?", english: "Where is it held?", category: "School & Clubs" },
    { finnish: "Paljonko maksaa?", english: "How much does it cost?", category: "School & Clubs" },
    { finnish: "Voiko maksaa osamaksulla?", english: "Can one pay in installments?", category: "School & Clubs" },
    { finnish: "Minulla on tapana kuunnella podcasteja, kun laitan ruokaa.", english: "I have a habit of listening to podcasts when I cook food.", category: "School & Clubs" },
    { finnish: "Olen tottunut käymään saunassa.", english: "I am used to going to the sauna.", category: "School & Clubs" },
    
    // 🛍️ OSTOKSET (Shopping)
    { finnish: "Onko sinulla käteistä?", english: "Do you have cash?", category: "Shopping" },
    { finnish: "Voinko maksaa kortilla?", english: "Can I pay by card?", category: "Shopping" },
    { finnish: "Voinko maksaa MobilePaylla?", english: "Can I pay with MobilePay?", category: "Shopping" },
    { finnish: "Onko tämä alennuksessa?", english: "Is this on sale?", category: "Shopping" },
    { finnish: "Onko tämä tarjouksessa?", english: "Is this on special offer?", category: "Shopping" },
    { finnish: "Voinko palauttaa tämän?", english: "Can I return this?", category: "Shopping" },
    { finnish: "Onko tämä kotimaista?", english: "Is this domestic?", category: "Shopping" },
    { finnish: "Onko tämä tuoretta?", english: "Is this fresh?", category: "Shopping" },
    { finnish: "Saanko pussin?", english: "Can I get a bag?", category: "Shopping" },
    { finnish: "Haluan ostaa tämän.", english: "I want to buy this.", category: "Shopping" },
    { finnish: "Katselen vain, kiitos.", english: "I'm just browsing, thanks.", category: "Shopping" },
    { finnish: "Kortilla vai käteisellä?", english: "By card or cash?", category: "Shopping" },
    { finnish: "Kiitos, hyvää päivänjatkoa!", english: "Thanks, have a nice day!", category: "Shopping" },
    { finnish: "Voisinko sovittaa tätä?", english: "Could I try this on?", category: "Shopping" },
    { finnish: "Tämä koko ei sovi minulle, tarvitsen pienemmän.", english: "This size doesn't fit me, I need a smaller one.", category: "Shopping" },
    { finnish: "Missä on sovituskoppi?", english: "Where is the fitting room?", category: "Shopping" },
    { finnish: "Haluaisin katsoa peiliin.", english: "I would like to look in the mirror.", category: "Shopping" },
    { finnish: "Tämä on liian pitkä.", english: "This is too long.", category: "Shopping" },
    { finnish: "Tämä on liian lyhyt.", english: "This is too short.", category: "Shopping" },
    { finnish: "Tämä on liian tiukka.", english: "This is too tight.", category: "Shopping" },
    { finnish: "Tämä on liian väljä.", english: "This is too loose.", category: "Shopping" },
    { finnish: "Tarvitsen tämän L-koossa.", english: "I need this in size L.", category: "Shopping" },
    { finnish: "Voinko maksaa käteisellä?", english: "Can I pay with cash?", category: "Shopping" },
    { finnish: "Kuinka paljon se maksaa?", english: "How much does it cost?", category: "Shopping" },
    { finnish: "Voinko maksaa osittain lahjakortilla?", english: "Can I pay partly with a gift card?", category: "Shopping" },
    { finnish: "Onko mahdollista ostaa osamaksulla?", english: "Is it possible to buy in installments?", category: "Shopping" },
    { finnish: "Tämä on tarjoushinta.", english: "This is a special price.", category: "Shopping" },
    { finnish: "Onko jäsenetuja?", english: "Are there member benefits?", category: "Shopping" },
    { finnish: "Haluaisin palauttaa tämän, paidassa on reikä.", english: "I would like to return this, there is a hole in the shirt.", category: "Shopping" },
    { finnish: "Haluaisin vaihtaa tämän puhelimen uuteen, näytössä on naarmu.", english: "I would like to exchange this phone for a new one, there is a scratch on the screen.", category: "Shopping" },
    { finnish: "En ole tyytyväinen laatuun.", english: "I am not satisfied with the quality.", category: "Shopping" },
    { finnish: "Paita on vääränkokoinen, tilasin S-koon.", english: "The shirt is the wrong size, I ordered size S.", category: "Shopping" },
    { finnish: "Tilaus saapui liian myöhään.", english: "The order arrived too late.", category: "Shopping" },
    { finnish: "Tuote on loppuunmyyty.", english: "The product is sold out.", category: "Shopping" },
    { finnish: "Onko se saatavilla verkossa?", english: "Is it available online?", category: "Shopping" },
    { finnish: "Takuu on vielä voimassa.", english: "The warranty is still valid.", category: "Shopping" },
    { finnish: "Kuinka pitkään takuu on voimassa?", english: "How long is the warranty valid?", category: "Shopping" },
    { finnish: "Mihin asti takuu on voimassa?", english: "Until when is the warranty valid?", category: "Shopping" },
    { finnish: "Saako tinkiä?", english: "Can one haggle?", category: "Shopping" },
    { finnish: "Voinko saada alennusta, jos ostan useita?", english: "Can I get a discount if I buy several?", category: "Shopping" },
    { finnish: "Voinko saada alennuksen, jos tuote on viallinen?", english: "Can I get a discount if the product is defective?", category: "Shopping" },
    { finnish: "Missä on vika?", english: "Where is the problem?", category: "Shopping" },
    { finnish: "Tuote on viallinen.", english: "The product is defective.", category: "Shopping" },
    { finnish: "Myyn vähän käytetyn, täysin toimivan pesukoneen.", english: "I'm selling a slightly used, fully functional washing machine.", category: "Shopping" },
    { finnish: "Suomessa juodaan paljon kahvia.", english: "A lot of coffee is drunk in Finland.", category: "Shopping" },
    { finnish: "Syödään tänään kalaa!", english: "Let's eat fish today!", category: "Shopping" },
    { finnish: "Me opiskellaan suomea.", english: "We study Finnish.", category: "Shopping" },
    { finnish: "Me syödään kalaa.", english: "We eat fish.", category: "Shopping" },
    { finnish: "Me ostetaan uudet huonekalut.", english: "We buy new furniture.", category: "Shopping" },
    { finnish: "Me ei osteta huonekaluja.", english: "We don't buy furniture.", category: "Shopping" },
    { finnish: "Suomessa maksetaan ruoasta enemmän kuin monessa muussa maassa.", english: "In Finland, more is paid for food than in many other countries.", category: "Shopping" },
    { finnish: "Terveellistä ruokaa suositellaan kaikille.", english: "Healthy food is recommended for everyone.", category: "Shopping" },
    { finnish: "Lihaa ei enää syödä yhtä paljon kuin ennen.", english: "Meat is no longer eaten as much as before.", category: "Shopping" },
    { finnish: "Halpoja vaatteita ei myydä kaupassa, vaan verkossa.", english: "Cheap clothes are not sold in stores, but online.", category: "Shopping" },
    { finnish: "Ei pysytä terveenä, jos ei syödä hyvin.", english: "One doesn't stay healthy if one doesn't eat well.", category: "Shopping" },
    { finnish: "Torilta ostetaan tuoreita vihanneksia.", english: "Fresh vegetables are bought from the market.", category: "Shopping" },
    { finnish: "Hinta koostuu kuljetuskuluista, veroista ja itse tuotteesta.", english: "The price consists of delivery costs, taxes and the product itself.", category: "Shopping" },
    { finnish: "Hintojen nousu johtuu mm. energiasta ja raaka-aineista.", english: "The rise in prices is due to, among other things, energy and raw materials.", category: "Shopping" },
    
    // 🏠 ASUMINEN (Housing)
    { finnish: "Voisitko hakea pyykit ajoissa, jotta muutkin mahtuvat kuivaushuoneeseen?", english: "Could you pick up the laundry on time so others can also fit in the drying room?", category: "Housing" },
    { finnish: "Viemme roskat jätekatokseen, pidetään rappu siistinä.", english: "We take the trash to the waste shed, let's keep the stairwell clean.", category: "Housing" },
    { finnish: "Voisitko välttää yömelua?", english: "Could you avoid nighttime noise?", category: "Housing" },
    { finnish: "Muuten joudun ottamaan yhteyttä isännöitsijään.", english: "Otherwise I'll have to contact the property manager.", category: "Housing" },
    { finnish: "Unohdin avaimet kotiin.", english: "I forgot the keys at home.", category: "Housing" },
    { finnish: "Voitteko lähettää korjaajan katsomaan pesukonetta?", english: "Could you send a repair person to look at the washing machine?", category: "Housing" },
    { finnish: "Asun Aleksanterinkatu 10 A:ssa, asunto 12.", english: "I live at Aleksanterinkatu 10 A, apartment 12.", category: "Housing" },
    { finnish: "Tämä on A-rappu.", english: "This is staircase A.", category: "Housing" },
    { finnish: "Asun ylimmässä kerroksessa.", english: "I live on the top floor.", category: "Housing" },
    { finnish: "Olen ulko-ovella.", english: "I am at the outer door.", category: "Housing" },
    { finnish: "En pääse rappuun sisään.", english: "I cannot get into the stairwell.", category: "Housing" },
    { finnish: "Paljonko oven avaaminen maksaa?", english: "How much does opening the door cost?", category: "Housing" },
    { finnish: "Voinko maksaa käteisellä?", english: "Can I pay with cash?", category: "Housing" },
    { finnish: "Voinko maksaa laskulla?", english: "Can I pay by invoice?", category: "Housing" },
    { finnish: "Missä on vika?", english: "Where is the problem?", category: "Housing" },
    { finnish: "Ikkuna on rikki.", english: "The window is broken.", category: "Housing" },
    { finnish: "Ikkuna ei pysy kiinni.", english: "The window won't stay closed.", category: "Housing" },
    { finnish: "Voisitteko lähettää korjaajan?", english: "Could you send a repair person?", category: "Housing" },
    { finnish: "Vesihana vuotaa, lattia kastuu.", english: "The faucet is leaking, the floor is getting wet.", category: "Housing" },
    { finnish: "Patteri on kylmä.", english: "The radiator is cold.", category: "Housing" },
    { finnish: "Voisitteko lähettää putkimiehen?", english: "Could you send a plumber?", category: "Housing" },
    { finnish: "Voisitteko tulla kiireellisesti korjaamaan hanan?", english: "Could you come urgently to fix the faucet?", category: "Housing" },
    { finnish: "Pääsen paikalle illalla.", english: "I can come to the location in the evening.", category: "Housing" },
    { finnish: "Aamulla on hammaslääkäri.", english: "In the morning I have a dentist appointment.", category: "Housing" },
    { finnish: "Jäteastia on niin täynnä, ettei kansi mene kiinni.", english: "The waste bin is so full that the lid won't close.", category: "Housing" },
    { finnish: "Pihalla haisee pahalta.", english: "It smells bad outside.", category: "Housing" },
    { finnish: "Milloin roska-auto tulee tyhjentämään?", english: "When will the garbage truck come to empty?", category: "Housing" },
    { finnish: "Kuuluuko pesu vuosimaksuun vai onko erillinen maksu?", english: "Is cleaning included in the annual fee or is there a separate charge?", category: "Housing" },
    { finnish: "Mitä pesu maksaa?", english: "How much does cleaning cost?", category: "Housing" },
    { finnish: "Kuuluuko pesu vuosimaksuun?", english: "Is cleaning included in the annual fee?", category: "Housing" },
    { finnish: "Muistaakseni.", english: "If I remember correctly.", category: "Housing" },
    { finnish: "Vielä yksi asia.", english: "One more thing.", category: "Housing" },
    { finnish: "Voinko maksaa vuokran tänään?", english: "Can I pay the rent today?", category: "Housing" },
    { finnish: "Sopimuksessa lukee, että vuokra pysyy samana 2 vuotta.", english: "The contract says that the rent stays the same for 2 years.", category: "Housing" },
    { finnish: "Onko koira sallittu?", english: "Is a dog allowed?", category: "Housing" },
    { finnish: "Lattialla on naarmuja – kirjataanko sopimukseen, ettei se ole minun vikani?", english: "There are scratches on the floor – should we write in the contract that it's not my fault?", category: "Housing" },
    { finnish: "Pyörä rappukäytävässä estää liikkumista.", english: "A bicycle in the stairwell blocks movement.", category: "Housing" },
    { finnish: "Asunnon pitäisi olla ainakin 50 neliötä.", english: "The apartment should be at least 50 square meters.", category: "Housing" },
    { finnish: "Vuokra korkeintaan 900 euroa.", english: "Rent at most 900 euros.", category: "Housing" },
    { finnish: "Asunnon ei tarvitse olla keskustassa.", english: "The apartment doesn't need to be in the city center.", category: "Housing" },
    { finnish: "Onko pesutupa?", english: "Is there a laundry room?", category: "Housing" },
    { finnish: "Onko autopaikka saatavilla?", english: "Is a parking space available?", category: "Housing" },
    { finnish: "Pitääkö maksaa vakuus?", english: "Do I need to pay a deposit?", category: "Housing" },
    { finnish: "Kuinka paljon?", english: "How much?", category: "Housing" },
    { finnish: "Pitääkö maksaa vesimaksu erikseen?", english: "Do I need to pay water fee separately?", category: "Housing" },
    { finnish: "Milloin asunto vapautuu?", english: "When does the apartment become available?", category: "Housing" },
    { finnish: "Irtisanomisaika?", english: "Notice period?", category: "Housing" },
    { finnish: "Toistaiseksi vai määräaikainen?", english: "Indefinite or fixed-term?", category: "Housing" },
    { finnish: "Voiko varata saunavuoron?", english: "Can one book a sauna time?", category: "Housing" },
    { finnish: "Hyvät bussiyhteydet.", english: "Good bus connections.", category: "Housing" },
    { finnish: "Juna-asema lähellä.", english: "Train station nearby.", category: "Housing" },
    { finnish: "Metroasema lähellä.", english: "Metro station nearby.", category: "Housing" },
    { finnish: "Pysäkki lähellä.", english: "Bus stop nearby.", category: "Housing" },
    { finnish: "Pyörätie lähellä.", english: "Bike path nearby.", category: "Housing" },
    { finnish: "Viiden minuutin päässä.", english: "Five minutes away.", category: "Housing" },
    { finnish: "Kävelymatkan päässä.", english: "A walking distance away.", category: "Housing" },
    { finnish: "Saunatilan vessaa saa käyttää vain omalla saunavuorolla.", english: "The sauna bathroom can only be used during one's own sauna time.", category: "Housing" },
    { finnish: "Roskikseen saa laittaa vain kotitalousjätettä.", english: "Only household waste can be put in the trash bin.", category: "Housing" },
    { finnish: "Muut jätteet asukkaat lajittelevat itse.", english: "Other waste residents sort themselves.", category: "Housing" },
    { finnish: "Ethän ruoki lintuja, ruoka houkuttelee hiiriä ja rottia.", english: "Don't feed birds, food attracts mice and rats.", category: "Housing" },
    { finnish: "On tärkeää viedä pullot kierrätyspisteeseen.", english: "It is important to take bottles to the recycling point.", category: "Housing" },
    { finnish: "Kotona lajittelemme jätettä.", english: "At home we sort waste.", category: "Housing" },
    
    // 🏖️ MATKAILU (Travel)
    { finnish: "Kaupungin arkkitehtuuri on modernia ja upeaa.", english: "The city's architecture is modern and beautiful.", category: "Travel" },
    { finnish: "Haluaisin kokeilla perinteistä ruokaa.", english: "I would like to try traditional food.", category: "Travel" },
    { finnish: "Tykkään lukemisesta.", english: "I like reading.", category: "Travel" },
    { finnish: "Tykkään lukea.", english: "I like to read.", category: "Travel" },
    { finnish: "Ihailen Suomen luontoa.", english: "I admire Finland's nature.", category: "Travel" },
    { finnish: "Nautin telttailusta.", english: "I enjoy camping.", category: "Travel" },
    { finnish: "Viihdyn rannalla kesällä.", english: "I enjoy being at the beach in summer.", category: "Travel" },
    { finnish: "Monelta juna lähtee Helsinkiin?", english: "What time does the train leave for Helsinki?", category: "Travel" },
    { finnish: "Onko suoria yhteyksiä?", english: "Are there direct connections?", category: "Travel" },
    { finnish: "Meitä on 5, tarvitaan viisi lippua.", english: "There are 5 of us, we need five tickets.", category: "Travel" },
    { finnish: "Matka epäonnistui, vaadin hyvitystä, koska kuljetus ei tullut.", english: "The trip failed, I demand compensation because the transport didn't come.", category: "Travel" },
    { finnish: "Kaupunki on tunnettu keskiaikaisista rakennuksista.", english: "The city is known for its medieval buildings.", category: "Travel" },
    { finnish: "Retkellä voi kävellä reiteillä, patikoida, kiivetä kallioille.", english: "On a hike one can walk on trails, hike, climb rocks.", category: "Travel" },
    { finnish: "Retkellä voi ihailla maisemia, tehdä nuotion merkityllä paikalla.", english: "On a hike one can admire scenery, make a campfire at a designated place.", category: "Travel" },
    { finnish: "Ole tarkka! Metsässä on käärmeitä ja punkkeja.", english: "Be careful! In the forest there are snakes and ticks.", category: "Travel" },
    { finnish: "Jos on hyvä tuuri, näkee peuran.", english: "If you have good luck, you'll see a deer.", category: "Travel" },
    { finnish: "Haluan vihreän teltan kahdelle.", english: "I want a green tent for two.", category: "Travel" },
    { finnish: "Onpa kallis!", english: "How expensive!", category: "Travel" },
    { finnish: "Onko teillä edullisempia vaihtoehtoja?", english: "Do you have cheaper alternatives?", category: "Travel" },
    { finnish: "Haluan vertailla, kiitos.", english: "I want to compare, thanks.", category: "Travel" },
    { finnish: "Saisiko tarjousta tähän malliin?", english: "Could I get an offer for this model?", category: "Travel" }
];

// Get all unique categories
function getCategories() {
    const categories = [...new Set(sentences.map(s => s.category))];
    return categories.sort();
}

// Filter sentences by category
function filterByCategory(category) {
    if (!category || category === "All") {
        return sentences;
    }
    return sentences.filter(s => s.category === category);
}

// Shuffle array function
function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}
